AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'client/**/*'
    - Guardfile

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Style/FileName:
  Exclude:
    - 'Gemfile'

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false
